#Plot4 on Household power consumption

dat<-read.table("household_power_consumption.txt", header=T, sep=";")
datSub<-dat[dat$Date %in% c("1/2/2007","2/2/2007"),]
date.time <- strptime(paste(datSub$Date, datSub$Time), format='%d/%m/%Y %H:%M:%S')
datSub$Global_active_power<-as.numeric(as.character(datSub$Global_active_power))
datSub$Sub_metering_1<-as.numeric(as.character(datSub$Sub_metering_1))
datSub$Sub_metering_2<-as.numeric(as.character(datSub$Sub_metering_2))
datSub$Voltage<-as.numeric(as.character(datSub$Voltage))
datSub$Global_reactive_power<-as.numeric(as.character(datSub$Global_reactive_power))
png("plot4.png",width = 480, height = 480)
par(mfcol = c(2, 2))
plot(date.time,datSub$Global_active_power, type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(date.time,datSub$Sub_metering_1,type="l",xlab="",ylab='Energy sub metering')
lines(date.time,datSub$Sub_metering_2,type="l",xlab="", col="red")
lines(date.time, datSub$Sub_metering_3,col="blue")
legend("topright",lty = 1, col = c("black", "red", "blue"), bty="n",legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(date.time,datSub$Voltage, type="l", ylab='Voltage', xlab="datetime")
plot(date.time,datSub$Global_reactive_power, type="l", ylab='Global_reactive_power', xlab="datetime")
dev.off()